### ISSUE TITLE
Pocket and Coin Positions

### ISSUE THREAD

**Issue by sb0210** [samiranrl/Carrom_rl#5]
The positions of the pockets and the coins are not symmetric. Is it intentional to add some randomness?
And the constants used in the board like damping, elasticity will remain constant throughout all the experiments or can change between experiments ?
And also, can you reduce the size of the board. Board goes out of the screen and we cannot reduce its size. As all the values are hard coded, it is difficult for us to change the board dimensions for testing.

**Comment by samiranrl** [comment]
1 - Not that intention, fixed pockets for now. For the **two-player** case, we will have 50:50 split: we will evaluate agents from both sides so that any bias due to  initial configuration is normalised
2 - They wont change
3 - For now could not find a bug free fix. If possible, try to use a system with a higher resolution. Will look into more approaches later. Leaving this thread open for now..

Thanks..

**Comment by AgarwalPragy** [comment]
Not only that, the striker location isn't symmetric either. For player-1, striker's Y coordinate is 145, while it is 136 for player-2.

This means that students need to take this inconsistency into consideration while making their agents. They will end up coding two agents instead of one. Plus, students have no way of finding out these inconsistencies to account for in their agent, apart from looking into the server's code.

Even though the evaluation will be fair, making two agents will be cumbersome.
Could you please look into this matter? It will be nice to have this resolved soon.

**Comment by samiranrl** [comment]
I have made the striker positions symmetric, will try to make starting coins too. is there anything else?
Thanks..

**Comment by AgarwalPragy** [comment]
Could you please take a look again. :(

In Utils.py, 145, 136 were changed to 140 which is fine.
However, the draw_arrow still uses 145, 136.
Also, the start_server.py still uses 145,136 to calculate striker-coin distance.

I seems like you've also fixed the bugs mentioned in this: https://github.com/samiranrl/Carrom_rl/pull/12
Thanks for that.

**Comment by samiranrl** [comment]
I fixed the above bugs.. 
Thanks for your help, ask me if there is anything else.
